// <auto-generated />
using FileStorage.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220410182928_SomeStorage")]
    partial class SomeStorage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FileStorage.Infrastructure.Data.Models.MetaInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DownloadNumber")
                        .HasColumnType("int");

                    b.Property<string>("FileCreationDate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("LastAccessTime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("MetaInformation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DownloadNumber = 0,
                            FileCreationDate = "2022/04/08",
                            FileExtension = ".txt",
                            FileName = "HelloWorld.txt",
                            FileSize = 174L,
                            LastAccessTime = "2022/04/08"
                        },
                        new
                        {
                            Id = 2,
                            DownloadNumber = 1,
                            FileCreationDate = "2022/04/08",
                            FileExtension = ".jpg",
                            FileName = "Universe.jpg",
                            FileSize = 4585350L,
                            LastAccessTime = "2022/04/08"
                        },
                        new
                        {
                            Id = 3,
                            DownloadNumber = 3,
                            FileCreationDate = "2022/04/08",
                            FileExtension = ".pdf",
                            FileName = "The_little_prince.pdf",
                            FileSize = 792631L,
                            LastAccessTime = "2022/04/08"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
